### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by YevhenZvieriev**
This update adds a detailed section to the README on how to debug Magento 2 cron jobs within a Docker environment using PhpStorm and Xdebug. This information is invaluable for developers who need to troubleshoot and debug scheduled tasks effectively.

* Simplifies Cron Debugging: Step-by-step instructions make it easier to configure and run debugging for Magento 2 cron jobs.

* Improves Developer Experience: With clear guidance, developers can save time and avoid common pitfalls during the debugging process.
* Enhanced Documentation: Having this information in the README provides quick access and ensures all developers working with the repository can easily set up cron debugging.

### CODE REVIEW

**Comment by YevhenZvieriev** [comment]
Hi everyone, I have an idea to expand the current README documentation to include a detailed section on how to debug individual Magento 2 cron jobs, rather than just the default cron group. 

While we currently have instructions on debugging the default cron group (it works **only** with the default cron group, honestly I don't know the reason), I recently discovered a way to debug individual cron jobs separately. 

This approach could provide developers with more precise control during the debugging process,  running only one cronjob, not the entire cron group.

Before I proceed with writing the detailed documentation for this, @markshust I wanted to ask if this would be useful. If so, I can include step-by-step instructions on how to configure PhpStorm and Xdebug to target specific cron jobs, which could improve troubleshooting and efficiency.

**Comment by markshust** [comment]
Thanks @YevhenZvieriev, I absolutely love this contribution!

However, the current README is a mess. It's super long and getting hard to read. I'd like to overhaul it with something like GitHub Pages (ex. https://gibinfrancis.medium.com/creating-structured-multi-page-documentation-with-github-pages-794b100a4941).

If ok, I'll sit on this PR for a bit until the docs are overhauled, but will gladly take stuff like this in, as I think it would make a great contribution to the repo. I think even a new "how to" section where we can place stuff like this in would be an awesome idea.

**Comment by markshust** [comment]
New ticket: https://github.com/markshust/docker-magento/issues/1244

**Comment by Nolwennig** [comment]
I'm just passing through here quickly to share this tool: https://readme.so/

**Comment by markshust** [comment]
@Nolwennig very cool -- I wish it did multiple pages!

**Pull request closed without merging**
