### PR TITLE
Finally, Varnish with https proxy

### PR DESCRIPTION
**Pull request by wigman**

### CODE REVIEW

**Comment by u-maxx** [comment]
I have fixed this merge conflict in https://github.com/wigman/docker-magento/pull/1

**Comment by markshust** [comment]
thank you much for the PR

the reason i haven't merged this yet is because i was thinking of implementing https via something like https://github.com/jwilder/nginx-proxy

i don't want too many changes which may confuse people. the reason for using nginx-proxy being we can run multiple docker projects/domains at once.

i'm still lagging on this ticket but will keep it open here.

**Comment by donnes** [comment]
@wigman Its possible to set multiple servers in `default.conf` from `proxy` image?

I have tried something like:

```
server {
  listen *:8443;
  server_name magento.local;
  ssl on;

  ssl_certificate /etc/nginx/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/certs/nginx.key;

  location / {
    proxy_pass http://192.168.15.201:8080;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 443;
    proxy_set_header Host $host;
    proxy_set_header Ssl-Offloaded 1;
    proxy_set_header DBG-SSL 1;
    fastcgi_param  HTTPS on;
  }
}

server {
  listen *:8443;
  server_name admin.magento.local;
  ssl on;

  ssl_certificate /etc/nginx/certs/nginx.crt;
  ssl_certificate_key /etc/nginx/certs/nginx.key;

  location / {
    proxy_pass http://varnish:80;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port 443;
    proxy_set_header Host $host;
    proxy_set_header Ssl-Offloaded 1;
    proxy_set_header DBG-SSL 1;
    fastcgi_param  HTTPS on;
  }
}
```

But the server for `admin.magento.local` return a NGINX 404 page.
The proxy for `magento.local` works fine.

Any idea?

**Comment by markshust** [comment]
I'm going to go ahead and decline this PR, unfortunately. I really don't see a need to use varnish in local dev, and this changeset adds a lot of config changes which I believe are going to be hard for a developer to understand/manage/update for day to day dev tasks (I have a hard time understanding what is going on, and unsure how to add things like multisites to this config, as varnish is a bit non-standard for local dev). Thanks for the contribution though and I hope you continue the work in varnish in your own fork.

**Comment by wigman** [comment]
No worries! Thanks for the heads up.

**Pull request closed without merging**
