### PR TITLE
set composer to latest v1

### PR DESCRIPTION
**Pull request by torhoehn**
Instead of updating the composer version flag regularly there is a flag to keep composer v1.

### CODE REVIEW

**Comment by markshust** [comment]
I think it's better if we actually keep a pegged version. I've had issues in the past where Composer was updated to a newer version, and it would break something in the dependency chain.

**Comment by torhoehn** [comment]
Okay, I understood. But with the release of v2 there shouldn't be any critical changes anymore.

**Review by markshust — APPROVED** [review]

**Comment by markshust** [comment]
Allright, good argument. All merged in, thanks! 👍

**Comment by torhoehn** [comment]
Thank you! Hopefully we have Composer v2 compatibility soon, so we can go back to a fixed version.

**Pull request merged**
