### PR TITLE
Added instructions for Linux install to README

### PR DESCRIPTION
**Pull request by kmilodenisglez**
added some dependencies that were needed to be able to run magento-docker successfully on a VPS with Debian GNU/Linux 12

### CODE REVIEW

**Comment by kmilodenisglez** [comment]
Updated the README.md with some dependencies that needed to be installed on a VPS with Debian GNU/Linux 12 installed.

Dependencies:

* curl 
* libnss3-tools 
* unzip 
* rsync

**Comment by markshust** [comment]
Thanks for the PR. I think it would make sense to move this to the Linux section at https://github.com/markshust/docker-magento#linux instead?

**Comment by kmilodenisglez** [comment]
> Thanks for the PR. I think it would make sense to move this to the Linux section at https://github.com/markshust/docker-magento#linux instead?
> 
> Also, there is only one item here so I don't think there is a need for a 1. bullet point.

yes you're right

**Comment by kmilodenisglez** [comment]
@markshust I just modified the readme.md of this same PR, check it and tell me.

**Comment by markshust** [comment]
@kmilodenisglez for some reason I cannot make changes to this PR myself, so can you make a couple more updates?

1. Move the block that added to just before the `#### The host.docker.internal hostname` line. The lines that followed your previous line block are basic lines about running Docker on Linux, and should come first.
2. Add a description after your heading to remain consistent with the rest of the documentation. It can say something like "docker-magento requires a few system dependencies to be installed on Linux in order to function properly. Please execute the following line from terminal to install these dependencies:"

**Comment by kmilodenisglez** [comment]
> @kmilodenisglez for some reason I cannot make changes to this PR myself, so can you make a couple more updates?
> 
> 1. Move the block that added to just before the `#### The host.docker.internal hostname` line. The lines that followed your previous line block are basic lines about running Docker on Linux, and should come first.
> 2. Add a description after your heading to remain consistent with the rest of the documentation. It can say something like "docker-magento requires a few system dependencies to be installed on Linux in order to function properly. Please execute the following line from terminal to install these dependencies:"

I already updated the readme

**Pull request merged**
