### PR TITLE
Fix dev-urn-catalog-generate

### PR DESCRIPTION
**Pull request by gander**
Sed manual: `-i[SUFFIX], --in-place[=SUFFIX]`
Remove `misc.xml` from container

### CODE REVIEW

**Comment by markshust** [comment]
@gander mac doesn't seem to have an `--in-place` argument, and it's a lot more common to use `-i`, so kept that flag as-is.

I'll merge in removing the unneeded misc.xml from the container though.

thanks!

**Comment by gander** [comment]
You make a mistake all the time. There is no space after `-i`! Check the documentation. I proposed a long name to make it more obvious.

https://linux.die.net/man/1/sed

**Comment by gander** [comment]
If the syntax of this command is different in mac and linux after all, you may need to distinguish in what system it is running?

**Comment by gander** [comment]
@markshust https://stackoverflow.com/a/4247319/4559414

**Comment by markshust** [comment]
I didn't make a mistake -- `-iCOMMAND` doesnt work on OSX, and neither does `--in-place` (that flag doesn't exist on OSX). it appears the `-i COMMAND` format only doesn't work on the GNU o/s, which I'm totally ok not supporting. I've always used `-i COMMAND` my entire life, so i know it works on almost all platforms.

**Comment by gander** [comment]
I understand that. What are you going to do about it? I suggest either detecting the system and running this command differently depending on it, or stop using this switch.

**Comment by markshust** [comment]
I'm going to live with it not working on GNU :) This is an acceptable bug for me to pass on. If someone else fixes it, I would gladly take in a PR for it.

**Pull request merged**
