### PR TITLE
add autocompletion for n98-magerun2

### PR DESCRIPTION
**Pull request by torhoehn**
This PR will add autocompletion to n98-magerun2 command line tool.

### CODE REVIEW

**Comment by markshust** [comment]
@torhoehn thanks for the contribution and i apologize for my belated reply!

where does this add the autocompletion? do you need to be within the docker container in order to use it?

**Comment by torhoehn** [comment]
@markshust Yes, you need to be within the docker container.

**Comment by markshust** [comment]
@torhoehn how do you use this? I installed this within the container but the original n98 script doesn't seem to have any sort of autocompleting going on.

**Comment by markshust** [comment]
I'm going to close this pending feedback on last comment (have conflicts going on right now atm also).

**Pull request closed without merging**
