### PR TITLE
Updated bin/remove and bin/status

### PR DESCRIPTION
**Pull request by rangerz**
Updated `bin/remove` to include `bin/removevolumes` function, and with `--all` can remove all images, containers, networks, and volumes
Also update README.md

Fixed issues: 
1. `docker-compose rm` only remove stoped containers. It should add `--stop`, if required, before removing.
2. `bin/removevolumes`, for volume naming rule need to use lowercase and skip dot `.` characters, and volume list should include rabbitmqdata, ssldata, and appvolumes
3. `bin/status` should appear mailhog status (define in `docker-compose.dev.yml`)

Because English is not my native language, please help me update these description if necessary.
Thanks.

### CODE REVIEW

**Comment by markshust** [comment]
I'm not sure I want to pull this in, I purposely created two separate remove scripts in the event you wanted to blow away the docker containers, but keep the data intact.

**Comment by canon-chen** [comment]
@markshust How about this, separate them to `bin/remove` and `bin/removeall` 
`bin/remove`: Stop all containers and remove containers
`bin/removeall`: Remove all containers, networks, volumes, and images

**Comment by rangerz** [comment]
@markshust How about this, separate them to `bin/remove` and `bin/removeall`
`bin/remove`: Stop all containers and remove containers
`bin/removeall`: Remove all containers, networks, volumes, and images

**Comment by markshust** [comment]
I like that! I'd also still keep the `bin/removevolumes` script there also.

**Pull request closed without merging**
