### PR TITLE
fix: prevent /etc/hosts domain duplication

### PR DESCRIPTION
**Pull request by ivanaugustobd**
Small patch to add the domain into _/etc/hosts_ only if it isn't already there

### CODE REVIEW

**Review by markshust — APPROVED** [review]

**Comment by markshust** [comment]
Very cool update, thanks!

**Comment by markshust** [comment]
Looks like this failed shellcheck. Can you check out this report and see if you can update? It should be a simple one.

Notice: ./compose/bin/setup-domain:8:14: note: Double quote to prevent globbing and word splitting. [SC2086]

**Comment by ivanaugustobd** [comment]
> Looks like this failed shellcheck. Can you check out this report and see if you can update? It should be a simple one.
> 
> Notice: ./compose/bin/setup-domain:8:14: note: Double quote to prevent globbing and word splitting. [SC2086]

Sure, done.

**Review by markshust — APPROVED** [review]

**Comment by markshust** [comment]
Appreciate it, all merged! Thanks again 👍

**Pull request merged**
