### PR TITLE
Create Dockerfile-with-ioncube

### PR DESCRIPTION
**Pull request by andrada88**
I am adding here a Dockerfile with ioncube extension installed, please add it where it is the best location for it ! 
It solved a problem related to an encrypted project code ... maybe it helps someone !

### CODE REVIEW

**Comment by rangerz** [comment]
Is this part not work for you ?
https://github.com/markshust/docker-magento/blob/3f8b3cb736c15d6f921e4b31c552ed4d4717c270/images/php/7.3/Dockerfile#L49-L57

**Comment by andrada88** [comment]
Unfortunately no, I used the original Dockerfile for php7.3 but I had no ioncube extension installed ...

**Comment by rangerz** [comment]
What's your markoshust/magento-php:7.3-fpm `version` ? ioncube works for me.

Try to use lastest version (markoshust/magento-php:7.3-fpm-12)

```
/> docker run -i -t markoshust/magento-php:7.3-fpm php -v
PHP 7.3.26 (cli) (built: Jan 12 2021 02:54:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.26, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.26, Copyright (c) 1999-2018, by Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with blackfire v1.49.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire

docker run -i -t markoshust/magento-php:7.3-fpm-12 php -v
PHP 7.3.27 (cli) (built: Feb  9 2021 20:10:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.50.0~linux-x64-non_zts73, https://blackfire.io, by Blackfire
```

**Comment by markshust** [comment]
Unable to confirm we need this fix, closing out as @rangerz says it works (thanks for confirming this).

**Pull request closed without merging**
