### PR TITLE
fix operation not permitted

### PR DESCRIPTION
**Pull request by piotrkwiecinski**
Possible fix for #385

@markshust @geoffjukes would you be able to test it?

### CODE REVIEW

**Comment by geoffjukes** [comment]
@piotrkwiecinski Progress....

Now the `fixowns` passes, but then fails with:

```
Correcting filesystem permissions...
find: ‘vendor’: No such file or directory
Filesystem permissions corrected.
Global composer auth already exists
Forcing reinstall of composer deps to ensure perms & reqs...
Changed current directory to /var/www/.composer
 [ErrorException]                                                             
 fopen(/var/www/.composer/cache/repo/http---repo.packagist.org/p-provider-2020-04.json): failed to open stream: Operation not permitted
```

**Comment by markshust** [comment]
@geoffjukes is your `~/.composer` or home `~` directory listed under Docker Preferences > Resources > File Sharing? Usually this is taken care of with `/Users`. Almost every error I've seen like this has stemmed from someone changing or removing the `/Users` line, as there should never be any permissions issues with this project (as long as you also don't use `bin/root` deviously).

Screen Shot 2021-02-03 at 9 18 32 AM

**Comment by geoffjukes** [comment]
@markshust `/Users` is showing under Resources. I'll keep poking around, see if something is wacky with Docker

**Comment by markshust** [comment]
Ok glad it's all resolved! I'll close out this PR as we don't likely need it then.

**Pull request closed without merging**
