### PR TITLE
Add support for OpenSearch

### PR DESCRIPTION
**Pull request by markshust**
I'd appreciate any help offered to replace Elasticsearch with OpenSearch for default/new Magento installs (still would like to support Elasticsearch for Magento versions < 2.4.4).

### CODE REVIEW

**Comment by rangerz** [comment]
Just provide helpful resourece: 
https://github.com/magento/magento-cloud-docker/blob/develop/images/opensearch/1.2/Dockerfile

**Comment by rangerz** [comment]
Required setting for `docker-compose.yml`
```yml
opensearch:
    environment:
      - DISABLE_SECURITY_PLUGIN=true
```

**Comment by bradleybrecher** [comment]
@markshust Do you plan on creating the `markoshust/magento-opensearch:1.2.4-0` docker image in your docker hub repository?

**Comment by markshust** [comment]
@bradleybrecher yes, I can't remember what issues I was actually having with this before (could have been many other updates I was merging in at that time), but I'll add this to my todo sometime this next week to get a new build image up (or perhaps we can just use the core/base image).

**Comment by bradleybrecher** [comment]
@markshust thank you.

I have it working with using the core/base image `opensearchproject/opensearch:1.2.4` but it would be nice to have the image be like the rest of the them (from your repository) even if it is just a basic fork.

Also will note from the current state of the pr I had to add https://github.com/markshust/docker-magento/pull/680#issuecomment-1200353125 to get it working

**Comment by markshust** [comment]
@bradleybrecher ok thanks much for the info. Will test this shortly!

**Pull request merged**
